pool:
  name: bso-docker
 
 
#Build the container image using Dockerfile, Tag the Image and Push the Image to DTR
steps:
- task: Maven@3
  displayName: 'Apigee Maven Build '
  inputs:
    options: 'clean package'
    publishJUnitResults: false

# PROD :: Goolge Container Registry 
- task: Docker@2
  displayName: 'GCR :: buildAndPush'
  inputs:
    containerRegistry: 'gcr-service-connection'
    repository: 'p-pm-do-8079/bloomberg-exchange-scheduler-service'
    Dockerfile: Dockerfile
    tags: $(build.buildid)

 

#Replace BuildNumber with required build number in deploymente.yaml file
- bash: 'bash -c "sed -i ''''s/DYNAMIC-TAG-NAME/$(build.buildid)/g'''' deployment/k8s-scheduler-deployment-prod.yaml"'
  displayName: 'Bash - Update Image Tag for PROD'
 
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
      deployment/k8s-scheduler-deployment-prod.yaml
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true

#Publish deployment.yaml as an artifiact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'