package com.bloomberg.services.datalicense.dlws.ps._20071001;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2019-10-15T12:45:33.758-05:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", name = "PerSecurityWS")
@XmlSeeAlso({ObjectFactory.class})
public interface PerSecurityWS {

    @WebMethod(action = "submitScheduledRequest")
    @RequestWrapper(localName = "submitScheduledRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitScheduledRequest")
    @ResponseWrapper(localName = "submitScheduledResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitScheduledResponse")
    public void submitScheduledRequest(
            @WebParam(mode = WebParam.Mode.OUT, name = "statusCode", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<ResponseStatus> statusCode,
            @WebParam(mode = WebParam.Mode.OUT, name = "requestId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> requestId,
            @WebParam(mode = WebParam.Mode.OUT, name = "responseId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> responseId
    );

    @WebMethod(action = "retrieveMmktBvalDealsUploadResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "retrieveMmktBvalDealsUploadResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveMmktBvalDealsUploadResponse retrieveMmktBvalDealsUploadResponse(
            @WebParam(partName = "parameters", name = "retrieveMmktBvalDealsUploadRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    RetrieveMmktBvalDealsUploadRequest parameters
    );

    @WebMethod(action = "submitGetFundamentalsRequest")
    @RequestWrapper(localName = "submitGetFundamentalsRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitGetFundamentalsRequest")
    @ResponseWrapper(localName = "submitGetFundamentalsResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitGetFundamentalsResponse")
    public void submitGetFundamentalsRequest(
            @WebParam(name = "headers", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    GetFundamentalsHeaders headers,
            @WebParam(name = "fields", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    Fields fields,
            @WebParam(name = "instruments", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    FundInstruments instruments,
            @WebParam(mode = WebParam.Mode.OUT, name = "statusCode", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<ResponseStatus> statusCode,
            @WebParam(mode = WebParam.Mode.OUT, name = "requestId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> requestId,
            @WebParam(mode = WebParam.Mode.OUT, name = "responseId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> responseId
    );

    @WebMethod(action = "retrieveOtcBvalDealsUploadResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "retrieveOtcBvalDealsUploadResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveOtcBvalDealsUploadResponse retrieveOtcBvalDealsUploadResponse(
            @WebParam(partName = "parameters", name = "retrieveOtcBvalDealsUploadRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    RetrieveOtcBvalDealsUploadRequest parameters
    );

    @WebMethod(action = "submitGetQuotesRequest")
    @RequestWrapper(localName = "submitGetQuotesRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitGetQuotesRequest")
    @ResponseWrapper(localName = "submitGetQuotesResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitGetQuotesResponse")
    public void submitGetQuotesRequest(
            @WebParam(name = "headers", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    QuotesHeaders headers,
            @WebParam(name = "instruments", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    Instruments instruments,
            @WebParam(mode = WebParam.Mode.OUT, name = "statusCode", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<ResponseStatus> statusCode,
            @WebParam(mode = WebParam.Mode.OUT, name = "requestId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> requestId,
            @WebParam(mode = WebParam.Mode.OUT, name = "responseId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> responseId
    );

    @WebMethod(action = "retrieveGetFundamentalsResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "retrieveGetFundamentalsResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveGetFundamentalsResponse retrieveGetFundamentalsResponse(
            @WebParam(partName = "parameters", name = "retrieveGetFundamentalsRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    RetrieveGetFundamentalsRequest parameters
    );

    @WebMethod(action = "retrieveCancelResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "retrieveCancelResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveCancelResponse retrieveCancelResponse(
            @WebParam(partName = "parameters", name = "retrieveCancelRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    RetrieveCancelRequest parameters
    );

    @WebMethod(action = "submitOtcBvalDealsUploadRequest")
    @RequestWrapper(localName = "submitOtcBvalDealsUploadRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitOtcBvalDealsUploadRequest")
    @ResponseWrapper(localName = "submitOtcBvalDealsUploadResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitOtcBvalDealsUploadResponse")
    public void submitOtcBvalDealsUploadRequest(
            @WebParam(name = "usernumber", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    int usernumber,
            @WebParam(name = "otcBvalHeaders", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    OtcBvalHeaders otcBvalHeaders,
            @WebParam(name = "fileContent", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    String fileContent,
            @WebParam(mode = WebParam.Mode.OUT, name = "statusCode", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<ResponseStatus> statusCode,
            @WebParam(mode = WebParam.Mode.OUT, name = "requestId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> requestId,
            @WebParam(mode = WebParam.Mode.OUT, name = "responseId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> responseId
    );

    @WebMethod(action = "retrieveGetAllQuotesResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "retrieveGetAllQuotesResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveGetAllQuotesResponse retrieveGetAllQuotesResponse(
            @WebParam(partName = "parameters", name = "retrieveGetAllQuotesRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    RetrieveGetAllQuotesRequest parameters
    );

    @WebMethod(action = "submitMmktBvalDealsUploadRequest")
    @RequestWrapper(localName = "submitMmktBvalDealsUploadRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitMmktBvalDealsUploadRequest")
    @ResponseWrapper(localName = "submitMmktBvalDealsUploadResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitMmktBvalDealsUploadResponse")
    public void submitMmktBvalDealsUploadRequest(
            @WebParam(name = "usernumber", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    int usernumber,
            @WebParam(name = "mmktBvalHeaders", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    MmktBvalHeaders mmktBvalHeaders,
            @WebParam(name = "fileContent", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    String fileContent,
            @WebParam(mode = WebParam.Mode.OUT, name = "statusCode", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<ResponseStatus> statusCode,
            @WebParam(mode = WebParam.Mode.OUT, name = "requestId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> requestId,
            @WebParam(mode = WebParam.Mode.OUT, name = "responseId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> responseId
    );

    @WebMethod(action = "retrieveGetHistoryResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "retrieveGetHistoryResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveGetHistoryResponse retrieveGetHistoryResponse(
            @WebParam(partName = "parameters", name = "retrieveGetHistoryRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    RetrieveGetHistoryRequest parameters
    );

    @WebMethod(action = "submitCancelRequest")
    @RequestWrapper(localName = "submitCancelRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitCancelRequest")
    @ResponseWrapper(localName = "submitCancelResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitCancelResponse")
    public void submitCancelRequest(
            @WebParam(name = "headers", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    CancelHeaders headers,
            @WebParam(mode = WebParam.Mode.OUT, name = "statusCode", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<ResponseStatus> statusCode,
            @WebParam(mode = WebParam.Mode.OUT, name = "requestId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> requestId,
            @WebParam(mode = WebParam.Mode.OUT, name = "responseId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> responseId
    );

    @WebMethod(action = "retrieveGetQuotesResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "retrieveGetQuotesResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveGetQuotesResponse retrieveGetQuotesResponse(
            @WebParam(partName = "parameters", name = "retrieveGetQuotesRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    RetrieveGetQuotesRequest parameters
    );

    @WebMethod(action = "submitGetHistoryRequest")
    @RequestWrapper(localName = "submitGetHistoryRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitGetHistoryRequest")
    @ResponseWrapper(localName = "submitGetHistoryResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitGetHistoryResponse")
    public void submitGetHistoryRequest(
            @WebParam(name = "headers", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    GetHistoryHeaders headers,
            @WebParam(name = "fields", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    Fields fields,
            @WebParam(name = "instruments", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    Instruments instruments,
            @WebParam(mode = WebParam.Mode.OUT, name = "statusCode", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<ResponseStatus> statusCode,
            @WebParam(mode = WebParam.Mode.OUT, name = "requestId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> requestId,
            @WebParam(mode = WebParam.Mode.OUT, name = "responseId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> responseId
    );

    @WebMethod(action = "retrieveScheduledResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "retrieveScheduledResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveScheduledResponse retrieveScheduledResponse(
            @WebParam(partName = "parameters", name = "retrieveScheduledRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    RetrieveScheduledRequest parameters
    );

    @WebMethod(action = "submitGetDataRequest")
    @RequestWrapper(localName = "submitGetDataRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitGetDataRequest")
    @ResponseWrapper(localName = "submitGetDataResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitGetDataResponse")
    public void submitGetDataRequest(
            @WebParam(name = "headers", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    GetDataHeaders headers,
            @WebParam(name = "fieldsets", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    BvalFieldSets fieldsets,
            @WebParam(name = "fields", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    Fields fields,
            @WebParam(name = "instruments", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    Instruments instruments,
            @WebParam(mode = WebParam.Mode.OUT, name = "statusCode", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<ResponseStatus> statusCode,
            @WebParam(mode = WebParam.Mode.OUT, name = "requestId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> requestId,
            @WebParam(mode = WebParam.Mode.OUT, name = "responseId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> responseId
    );

    @WebMethod(action = "getCorrections")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getCorrectionsResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public GetCorrectionsResponse getCorrections(
            @WebParam(partName = "parameters", name = "getCorrectionsRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    GetCorrectionsRequest parameters
    );

    @WebMethod(action = "submitGetAllQuotesRequest")
    @RequestWrapper(localName = "submitGetAllQuotesRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitGetAllQuotesRequest")
    @ResponseWrapper(localName = "submitGetAllQuotesResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitGetAllQuotesResponse")
    public void submitGetAllQuotesRequest(
            @WebParam(name = "headers", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    QuotesHeaders headers,
            @WebParam(name = "instruments", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    Instruments instruments,
            @WebParam(mode = WebParam.Mode.OUT, name = "statusCode", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<ResponseStatus> statusCode,
            @WebParam(mode = WebParam.Mode.OUT, name = "requestId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> requestId,
            @WebParam(mode = WebParam.Mode.OUT, name = "responseId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> responseId
    );

    @WebMethod(action = "retrieveGetCompanyResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "retrieveGetCompanyResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveGetCompanyResponse retrieveGetCompanyResponse(
            @WebParam(partName = "parameters", name = "retrieveGetCompanyRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    RetrieveGetCompanyRequest parameters
    );

    @WebMethod(action = "submitGetActionsRequest")
    @RequestWrapper(localName = "submitGetActionsRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitGetActionsRequest")
    @ResponseWrapper(localName = "submitGetActionsResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitGetActionsResponse")
    public void submitGetActionsRequest(
            @WebParam(name = "headers", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    GetActionsHeaders headers,
            @WebParam(name = "instruments", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    Instruments instruments,
            @WebParam(mode = WebParam.Mode.OUT, name = "statusCode", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<ResponseStatus> statusCode,
            @WebParam(mode = WebParam.Mode.OUT, name = "requestId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> requestId,
            @WebParam(mode = WebParam.Mode.OUT, name = "responseId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> responseId
    );

    @WebMethod(action = "retrieveOtcbvalUploadResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "retrieveOtcbvalUploadResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveOtcbvalUploadResponse retrieveOtcbvalUploadResponse(
            @WebParam(partName = "parameters", name = "retrieveOtcbvalUploadRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    RetrieveOtcbvalUploadRequest parameters
    );

    @WebMethod(action = "retrieveGetActionsResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "retrieveGetActionsResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveGetActionsResponse retrieveGetActionsResponse(
            @WebParam(partName = "parameters", name = "retrieveGetActionsRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    RetrieveGetActionsRequest parameters
    );

    @WebMethod(action = "getFields")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getFieldsResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public GetFieldsResponse getFields(
            @WebParam(partName = "parameters", name = "getFieldsRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    GetFieldsRequest parameters
    );

    @WebMethod(action = "submitGetCompanyRequest")
    @RequestWrapper(localName = "submitGetCompanyRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitGetCompanyRequest")
    @ResponseWrapper(localName = "submitGetCompanyResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitGetCompanyResponse")
    public void submitGetCompanyRequest(
            @WebParam(name = "headers", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    GetCompanyHeaders headers,
            @WebParam(name = "fieldset", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    FieldSet fieldset,
            @WebParam(name = "fields", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    Fields fields,
            @WebParam(name = "instruments", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    Instruments instruments,
            @WebParam(mode = WebParam.Mode.OUT, name = "statusCode", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<ResponseStatus> statusCode,
            @WebParam(mode = WebParam.Mode.OUT, name = "requestId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> requestId,
            @WebParam(mode = WebParam.Mode.OUT, name = "responseId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> responseId
    );

    @WebMethod(action = "getPortfolioValidation")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getPortfolioValidationResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public GetPortfolioValidationResponse getPortfolioValidation(
            @WebParam(partName = "parameters", name = "getPortfolioValidationRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    GetPortfolioValidationRequest parameters
    );

    @WebMethod(action = "retrieveGetDataResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "retrieveGetDataResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveGetDataResponse retrieveGetDataResponse(
            @WebParam(partName = "parameters", name = "retrieveGetDataRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    RetrieveGetDataRequest parameters
    );

    @WebMethod(action = "submitOtcbvalUploadRequest")
    @RequestWrapper(localName = "submitOtcbvalUploadRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitOtcbvalUploadRequest")
    @ResponseWrapper(localName = "submitOtcbvalUploadResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", className = "com.bloomberg.services.datalicense.dlws.ps._20071001.SubmitOtcbvalUploadResponse")
    public void submitOtcbvalUploadRequest(
            @WebParam(name = "usernumber", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    int usernumber,
            @WebParam(name = "otcBvalHeaders", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    OtcBvalHeaders otcBvalHeaders,
            @WebParam(name = "fileContent", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    String fileContent,
            @WebParam(mode = WebParam.Mode.OUT, name = "statusCode", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<ResponseStatus> statusCode,
            @WebParam(mode = WebParam.Mode.OUT, name = "requestId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> requestId,
            @WebParam(mode = WebParam.Mode.OUT, name = "responseId", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
                    javax.xml.ws.Holder<String> responseId
    );
}
